swagger: "2.0"
info:
  title: Sample API
  description: Home Page Test
  version: 1.0.0

host: 
basePath:
schemes:
  - http

paths:
  /:
    get:
      summary: Return Olá Mundo
      description: Test Home Page
      produces:
        - application/json
        - application/yaml
      responses:
        200:
          description: Your email has arrived! 